const express=require('express'); const http=require('http'); const {Server}=require('socket.io'); const path=require('path');
const app=express(), server=http.createServer(app), io=new Server(server); app.use(express.static(path.join(__dirname,'public')));
const rooms=new Map(); const code=()=>Math.random().toString(36).slice(2,8).toUpperCase();
const safe=s=>String(s||'Player').replace(/[<>]/g,'').slice(0,14)||'Player';
function view(r){return {code:r.code,host:r.host,started:r.started,settings:r.settings,players:[...r.players.values()].map(p=>({id:p.id,name:p.name,color:p.color,hat:p.hat,pet:p.pet,alive:p.alive,x:p.x,y:p.y,dead:p.dead,done:p.done}))};}
function emit(r){io.to(r.code).emit('room',view(r));}
function win(r){if(!r.started)return;const ps=[...r.players.values()], alive=ps.filter(p=>p.alive), imps=alive.filter(p=>p.role==='Impostor'), crew=alive.filter(p=>p.role!=='Impostor'); if(!imps.length)return end(r,'CREW VICTORY','All Impostors were eliminated.'); if(imps.length>=crew.length)return end(r,'IMPOSTOR VICTORY','Impostors reached parity.'); const crewAll=ps.filter(p=>p.role!=='Impostor'); if(crewAll.length&&crewAll.every(p=>p.done>=7))end(r,'CREW VICTORY','All crew tasks were completed.');}
function end(r,title,text){r.started=false; io.to(r.code).emit('victory',{title,text}); setTimeout(()=>emit(r),3500);}
io.on('connection',s=>{
 s.on('host',d=>{let c;do c=code();while(rooms.has(c)); const r={code:c,host:s.id,started:false,settings:{difficulty:'Medium',voteTime:45,impostors:1,engineers:0,scientists:0,judges:0,defenders:0},players:new Map(),meeting:null}; rooms.set(c,r); r.players.set(s.id,{id:s.id,name:safe(d.name),color:d.color||'#d94b50',hat:d.hat||'none',pet:d.pet||'none',alive:true,dead:false,x:1450,y:760,done:0,role:null,judgeUsed:false}); s.join(c);s.data.room=c;emit(r)});
 s.on('join',d=>{const c=String(d.code||'').toUpperCase(),r=rooms.get(c);if(!r)return s.emit('errorMsg','Room not found.');if(r.started)return s.emit('errorMsg','Match already started.');if(r.players.size>=10)return s.emit('errorMsg','Room is full.');r.players.set(s.id,{id:s.id,name:safe(d.name),color:d.color||'#3978d6',hat:d.hat||'none',pet:d.pet||'none',alive:true,dead:false,x:1450,y:760,done:0,role:null,judgeUsed:false});s.join(c);s.data.room=c;emit(r)});
 s.on('settings',d=>{const r=rooms.get(s.data.room);if(!r||r.host!==s.id||r.started)return;Object.assign(r.settings,d);emit(r)});
 s.on('start',()=>{const r=rooms.get(s.data.room);if(!r||r.host!==s.id||r.started)return;const ps=[...r.players.values()],q=r.settings,total=(+q.impostors||0)+(+q.engineers||0)+(+q.scientists||0)+(+q.judges||0)+(+q.defenders||0);if(ps.length<2)return s.emit('errorMsg','Need at least 2 players.');if((+q.impostors||0)<1||total>ps.length)return s.emit('errorMsg','Role counts do not fit the lobby.');let deck=[];for(const [role,key] of [['Impostor','impostors'],['Engineer','engineers'],['Scientist','scientists'],['Judge','judges'],['Defender','defenders']])for(let i=0;i<(+q[key]||0);i++)deck.push(role);while(deck.length<ps.length)deck.push('Crewmate');deck.sort(()=>Math.random()-.5);ps.forEach((p,i)=>{p.role=deck[i];p.alive=true;p.dead=false;p.done=0;p.judgeUsed=false;p.x=1450+(i%4)*55;p.y=760+Math.floor(i/4)*55;io.to(p.id).emit('role',{role:p.role});});r.started=true;r.meeting=null;emit(r);io.to(r.code).emit('started',{settings:r.settings});});
 s.on('move',d=>{const r=rooms.get(s.data.room),p=r?.players.get(s.id);if(!r?.started||!p)return;p.x=Math.max(80,Math.min(3020,+d.x||p.x));p.y=Math.max(80,Math.min(2020,+d.y||p.y));p.color=d.color||p.color;p.hat=d.hat||p.hat;p.pet=d.pet||p.pet;s.to(r.code).emit('moved',{id:p.id,x:p.x,y:p.y,color:p.color,hat:p.hat,pet:p.pet,alive:p.alive});});
 s.on('taskDone',()=>{const r=rooms.get(s.data.room),p=r?.players.get(s.id);if(!r?.started||!p||p.role==='Impostor'||p.done>=7)return;p.done++;io.to(r.code).emit('taskProgress',{id:p.id,done:p.done,total:[...r.players.values()].filter(x=>x.role!=='Impostor').length*7});win(r)});
 s.on('kill',target=>{const r=rooms.get(s.data.room),p=r?.players.get(s.id),v=r?.players.get(target);if(!r?.started||!p||!v||p.role!=='Impostor'||!p.alive||!v.alive||v.role==='Impostor')return;if(Math.hypot(p.x-v.x,p.y-v.y)>105)return;v.alive=false;v.dead=true;io.to(r.code).emit('killed',{id:v.id,x:v.x,y:v.y,name:v.name,color:v.color});win(r)});
 s.on('meeting',d=>{const r=rooms.get(s.data.room),p=r?.players.get(s.id);if(!r?.started||!p||!p.alive||r.meeting)return;r.meeting={votes:new Map(),reason:safe(d.reason||'Emergency meeting'),ends:Date.now()+Math.max(10,Math.min(180,+r.settings.voteTime||45))*1000};io.to(r.code).emit('meeting',{reason:r.meeting.reason,ends:r.meeting.ends,players:[...r.players.values()].filter(x=>x.alive).map(x=>({id:x.id,name:x.name}))});setTimeout(()=>finishMeeting(r),Math.max(10,+r.settings.voteTime||45)*1000+200)});
 s.on('vote',target=>{const r=rooms.get(s.data.room),p=r?.players.get(s.id);if(!r?.meeting||!p?.alive||r.meeting.votes.has(s.id))return;if(target!==null&&!r.players.get(target)?.alive)return;r.meeting.votes.set(s.id,target);io.to(r.code).emit('voted',{id:s.id});if(r.meeting.votes.size>=[...r.players.values()].filter(x=>x.alive).length)finishMeeting(r)});
 s.on('judge',target=>{const r=rooms.get(s.data.room),p=r?.players.get(s.id),v=r?.players.get(target);if(!r?.meeting||!p?.alive||p.role!=='Judge'||p.judgeUsed||!v?.alive||v.id===p.id)return;p.judgeUsed=true;io.to(r.code).emit('hammer',{target:v.id});setTimeout(()=>{if(v.role==='Impostor'){v.alive=false;v.dead=true;io.to(r.code).emit('judgeResult',{text:`${v.name} was an Impostor.`,dead:v.id});}else{p.alive=false;p.dead=true;io.to(r.code).emit('judgeResult',{text:`Wrong judgment — ${p.name} was eliminated.`,dead:p.id});}win(r)},700)});
 s.on('disconnect',()=>{const r=rooms.get(s.data.room);if(!r)return;r.players.delete(s.id);if(!r.players.size){rooms.delete(r.code);return}if(r.host===s.id)r.host=r.players.keys().next().value;emit(r)});
});
function finishMeeting(r){if(!r.meeting)return;const votes=[...r.meeting.votes.entries()],counts={};for(const [,t] of votes){const k=t||'SKIP';counts[k]=(counts[k]||0)+1}let max=Math.max(0,...Object.values(counts)),tops=Object.keys(counts).filter(k=>counts[k]===max),ejected=tops.length===1&&tops[0]!=='SKIP'?tops[0]:null;if(ejected&&r.players.get(ejected)){r.players.get(ejected).alive=false;r.players.get(ejected).dead=true}io.to(r.code).emit('voteResult',{votes:votes.map(([v,t])=>({voter:r.players.get(v)?.name||'Left',target:t?r.players.get(t)?.name||'Left':'SKIP'})),ejected:ejected?r.players.get(ejected)?.name:null});r.meeting=null;win(r);setTimeout(()=>emit(r),2500)}
server.listen(process.env.PORT||3000,'0.0.0.0',()=>console.log('SpaceCrew multiplayer running on port '+(process.env.PORT||3000)));
