const express=require('express');
const http=require('http');
const {Server}=require('socket.io');
const path=require('path');
const app=express(),server=http.createServer(app),io=new Server(server);
app.use(express.static(__dirname));

const rooms=new Map();
const ROOMS=[[120,420,430,430],[610,160,470,360],[640,650,420,340],[1160,480,650,520],[1930,250,430,340],[2520,520,450,500],[1910,800,430,330],[1050,1190,430,350],[1570,1280,650,480],[480,1050,400,330],[520,1540,500,370],[2350,1320,450,350]];
const CORR=[[250,590,2750,170],[760,280,170,1500],[1380,650,170,800],[2010,370,170,1100],[650,1290,1900,180]];
const PROPS=[[1540,1400,55,48],[1610,1400,55,48],[1690,1400,65,50],[1880,1580,60,50],[1970,1580,65,50],[1300,560,100,50],[1500,560,100,50],[730,410,120,70],[680,1670,125,75],[2290,1460,55,90],[2390,1460,55,90]];
const TASKS=[[300,610],[790,310],[790,810],[1370,640],[1610,820],[2070,400],[2740,760],[2080,930],[1240,1350],[1770,1480],[700,1200],[760,1710],[2530,1460],[2450,1570]];
const VENTS=[[355,700],[850,430],[890,850],[1320,850],[1700,650],[2110,500],[2710,850],[2070,1000],[1180,1360],[1810,1570],[710,1230],[820,1720],[2530,1510]];
const EM=[1480,735];
const inside=(x,y,r,m=0)=>x>r[0]-m&&x<r[0]+r[2]+m&&y>r[1]-m&&y<r[1]+r[3]+m;
function floor(x,y){return ROOMS.some(r=>inside(x,y,[r[0]+18,r[1]+18,r[2]-36,r[3]-36]))||CORR.some(r=>inside(x,y,[r[0]+18,r[1]+18,r[2]-36,r[3]-36]));}
function walkable(x,y){return floor(x,y)&&!PROPS.some(r=>inside(x,y,r,22));}
const code=()=>Math.random().toString(36).slice(2,8).toUpperCase();
const safe=s=>String(s||'Player').replace(/[<>]/g,'').slice(0,14)||'Player';
const dist=(a,b)=>Math.hypot(a.x-b[0],a.y-b[1]);
function publicPlayer(p){return{id:p.id,name:p.name,color:p.color,hat:p.hat,pet:p.pet,alive:p.alive,x:p.x,y:p.y,done:p.done};}
function view(r){return{code:r.code,host:r.host,started:r.started,settings:r.settings,bodies:r.bodies.map(b=>({...b})),players:[...r.players.values()].map(publicPlayer)};}
function emit(r){io.to(r.code).emit('room',view(r));}
function end(r,title,text){if(!r.started)return;r.started=false;io.to(r.code).emit('victory',{title,text});setTimeout(()=>emit(r),3500);}
function win(r){if(!r.started)return;const ps=[...r.players.values()],alive=ps.filter(p=>p.alive),imps=alive.filter(p=>p.role==='Impostor'),crew=alive.filter(p=>p.role!=='Impostor');if(!imps.length)return end(r,'CREW VICTORY','All Impostors were eliminated.');if(imps.length>=crew.length)return end(r,'IMPOSTOR VICTORY','Impostors reached parity.');const crewAll=ps.filter(p=>p.role!=='Impostor');if(crewAll.length&&crewAll.every(p=>p.done>=7))end(r,'CREW VICTORY','All crew tasks were completed.');}
function shuffled(n){let a=Array.from({length:n},(_,i)=>i);for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function playerBase(id,d,color){return{id,name:safe(d.name),color:d.color||color,hat:d.hat||'none',pet:d.pet||'none',alive:true,x:1450,y:760,done:0,role:null,judgeUsed:false,assignments:[]};}

io.on('connection',s=>{
 s.on('host',d=>{let c;do c=code();while(rooms.has(c));const r={code:c,host:s.id,started:false,settings:{difficulty:'Medium',voteTime:45,impostors:1,engineers:0,scientists:0,judges:0,defenders:0},players:new Map(),meeting:null,bodies:[]};rooms.set(c,r);r.players.set(s.id,playerBase(s.id,d,'#d94b50'));s.join(c);s.data.room=c;emit(r);});
 s.on('join',d=>{const c=String(d.code||'').toUpperCase(),r=rooms.get(c);if(!r)return s.emit('errorMsg','Room not found.');if(r.started)return s.emit('errorMsg','Match already started.');if(r.players.size>=10)return s.emit('errorMsg','Room is full.');r.players.set(s.id,playerBase(s.id,d,'#3978d6'));s.join(c);s.data.room=c;emit(r);});
 s.on('settings',d=>{const r=rooms.get(s.data.room);if(!r||r.host!==s.id||r.started)return;for(const k of ['difficulty','voteTime','impostors','engineers','scientists','judges','defenders'])if(d[k]!==undefined)r.settings[k]=d[k];emit(r);});
 s.on('start',()=>{const r=rooms.get(s.data.room);if(!r||r.host!==s.id||r.started)return;const ps=[...r.players.values()],q=r.settings,total=(+q.impostors||0)+(+q.engineers||0)+(+q.scientists||0)+(+q.judges||0)+(+q.defenders||0);if(ps.length<2)return s.emit('errorMsg','Need at least 2 players.');if((+q.impostors||0)<1||total>ps.length)return s.emit('errorMsg','Role counts do not fit the lobby.');let deck=[];for(const [role,key] of [['Impostor','impostors'],['Engineer','engineers'],['Scientist','scientists'],['Judge','judges'],['Defender','defenders']])for(let i=0;i<(+q[key]||0);i++)deck.push(role);while(deck.length<ps.length)deck.push('Crewmate');deck=shuffled(deck.length).map(i=>deck[i]);r.bodies=[];ps.forEach((p,i)=>{p.role=deck[i];p.alive=true;p.done=0;p.judgeUsed=false;p.x=1450+(i%4)*55;p.y=760+Math.floor(i/4)*55;p.assignments=p.role==='Impostor'?[]:shuffled(TASKS.length).slice(0,7);io.to(p.id).emit('role',{role:p.role,assignments:p.assignments,settings:r.settings});});r.started=true;r.meeting=null;emit(r);io.to(r.code).emit('started',{settings:r.settings});});
 s.on('move',d=>{const r=rooms.get(s.data.room),p=r?.players.get(s.id);if(!r?.started||!p)return;let nx=Math.max(80,Math.min(3020,+d.x||p.x)),ny=Math.max(80,Math.min(2020,+d.y||p.y));if(!p.alive||walkable(nx,ny)){p.x=nx;p.y=ny;}p.color=d.color||p.color;p.hat=d.hat||p.hat;p.pet=d.pet||p.pet;s.to(r.code).emit('moved',{id:p.id,x:p.x,y:p.y,color:p.color,hat:p.hat,pet:p.pet,alive:p.alive});});
 s.on('taskDone',taskId=>{const r=rooms.get(s.data.room),p=r?.players.get(s.id),i=+taskId;if(!r?.started||!p||p.role==='Impostor'||!p.alive||p.done>=7||!p.assignments.includes(i)||!TASKS[i]||dist(p,TASKS[i])>90)return;p.assignments=p.assignments.filter(x=>x!==i);p.done++;io.to(p.id).emit('assignments',{assignments:p.assignments});io.to(r.code).emit('taskProgress',{id:p.id,done:p.done,total:[...r.players.values()].filter(x=>x.role!=='Impostor').length*7});win(r);});
 s.on('vent',idx=>{const r=rooms.get(s.data.room),p=r?.players.get(s.id),i=+idx;if(!r?.started||!p||!p.alive||!(p.role==='Impostor'||p.role==='Engineer')||!VENTS[i]||dist(p,VENTS[i])>90)return;const next=VENTS[(i+1)%VENTS.length];p.x=next[0];p.y=next[1];io.to(r.code).emit('moved',{id:p.id,x:p.x,y:p.y,color:p.color,hat:p.hat,pet:p.pet,alive:p.alive});io.to(p.id).emit('vented',{x:p.x,y:p.y});});
 s.on('kill',target=>{const r=rooms.get(s.data.room),p=r?.players.get(s.id),v=r?.players.get(target);if(!r?.started||!p||!v||p.role!=='Impostor'||!p.alive||!v.alive||v.role==='Impostor'||Math.hypot(p.x-v.x,p.y-v.y)>105)return;v.alive=false;const body={id:'b'+Date.now()+Math.random(),victim:v.id,x:v.x,y:v.y,name:v.name,color:v.color,reported:false};r.bodies.push(body);io.to(r.code).emit('killed',{id:v.id,body});win(r);});
 s.on('report',bodyId=>{const r=rooms.get(s.data.room),p=r?.players.get(s.id),b=r?.bodies.find(x=>x.id===bodyId);if(!r?.started||!p?.alive||r.meeting||!b||b.reported||Math.hypot(p.x-b.x,p.y-b.y)>95)return;b.reported=true;startMeeting(r,`${p.name} reported ${b.name}!`);});
 s.on('meeting',()=>{const r=rooms.get(s.data.room),p=r?.players.get(s.id);if(!r?.started||!p?.alive||r.meeting||Math.hypot(p.x-EM[0],p.y-EM[1])>110)return;startMeeting(r,`${p.name} called an emergency meeting.`);});
 s.on('vote',target=>{const r=rooms.get(s.data.room),p=r?.players.get(s.id);if(!r?.meeting||!p?.alive||r.meeting.votes.has(s.id))return;if(target!==null&&!r.players.get(target)?.alive)return;r.meeting.votes.set(s.id,target);io.to(r.code).emit('voted',{id:s.id});if(r.meeting.votes.size>=[...r.players.values()].filter(x=>x.alive).length)finishMeeting(r);});
 s.on('judge',target=>{const r=rooms.get(s.data.room),p=r?.players.get(s.id),v=r?.players.get(target);if(!r?.meeting||!p?.alive||p.role!=='Judge'||p.judgeUsed||!v?.alive||v.id===p.id)return;p.judgeUsed=true;io.to(r.code).emit('hammer',{target:v.id});setTimeout(()=>{if(v.role==='Impostor'){v.alive=false;io.to(r.code).emit('judgeResult',{text:`${v.name} was an Impostor.`,dead:v.id});}else{p.alive=false;io.to(r.code).emit('judgeResult',{text:`Wrong judgment — ${p.name} was eliminated.`,dead:p.id});}emit(r);win(r);},700);});
 s.on('disconnect',()=>{const r=rooms.get(s.data.room);if(!r)return;r.players.delete(s.id);if(!r.players.size){rooms.delete(r.code);return;}if(r.host===s.id)r.host=r.players.keys().next().value;emit(r);});
});
function startMeeting(r,reason){r.meeting={votes:new Map(),reason,ends:Date.now()+Math.max(10,Math.min(180,+r.settings.voteTime||45))*1000};io.to(r.code).emit('meeting',{reason,ends:r.meeting.ends,players:[...r.players.values()].filter(x=>x.alive).map(x=>({id:x.id,name:x.name}))});setTimeout(()=>finishMeeting(r),Math.max(10,+r.settings.voteTime||45)*1000+200);}
function finishMeeting(r){if(!r.meeting)return;const votes=[...r.meeting.votes.entries()],counts={};for(const [,t] of votes){const k=t||'SKIP';counts[k]=(counts[k]||0)+1;}const max=Math.max(0,...Object.values(counts)),tops=Object.keys(counts).filter(k=>counts[k]===max),ejected=tops.length===1&&tops[0]!=='SKIP'?tops[0]:null;if(ejected&&r.players.get(ejected))r.players.get(ejected).alive=false;io.to(r.code).emit('voteResult',{votes:votes.map(([v,t])=>({voter:r.players.get(v)?.name||'Left',target:t?r.players.get(t)?.name||'Left':'SKIP'})),ejected:ejected?r.players.get(ejected)?.name:null});r.meeting=null;win(r);setTimeout(()=>emit(r),2500);}
server.listen(process.env.PORT||3000,'0.0.0.0',()=>console.log('SpaceCrew multiplayer running on port '+(process.env.PORT||3000)));
